#!/bin/bash
set -e
export GHERKIN_WIRE_SOCKET="{SOCKET}"

./{STEPS} &

mkdir -p "${TEST_UNDECLARED_OUTPUTS_DIR}"
OUTPUT_FILE="${TEST_UNDECLARED_OUTPUTS_DIR}/{OUTPUT_FILENAME}"

./{CUCUMBER_RUBY} -r $RUNFILES_DIR/{FEATURE_DIR} {ADDITIONAL_CUCUMBER_ARGS} --out=${OUTPUT_FILE} $RUNFILES_DIR/{FEATURE_DIR}

cat ${OUTPUT_FILE}
