name: Bazel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Checkout source
        uses: actions/checkout@v5

      - uses: bazel-contrib/setup-bazel@0.15.0

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Test
        run: |
          cd examples
          bazel test //... --test_output=all  

      - name: Test Json
        run: |
          cd examples
          bazel test --config=json //... --test_output=all  
